# Generated by Django 3.2.5 on 2021-11-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='body',
            field=models.TextField(default='Thank you, next'),
            preserve_default=False,
        ),
    ]
