# Generated by Django 3.2.5 on 2022-02-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_rename_thumb_articles_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
